### ISSUE TITLE
add option for empty tag default value

### ISSUE THREAD

**Issue by futurist** [foxdonut/seview#1]
Like `m('')` -> `<div>`, can add an option as below:

```js
sv(func, {emptyTag: 'div'})
```
So `['', 'Hello']` result in `<div>Hello</div>`

Is it make sense?

**Comment by futurist** [comment]
Oh, I think this option is not make sense, sorry for the noise 😄

**Comment by foxdonut** [comment]
Hi @futurist 

That should already work. If you look in the readme under the [Tag section](https://github.com/foxdonut/seview#tag):

> default tag is "div", so you can write "", ".highlighted", "#home", etc.

So indeed if you write `['', 'Hello']` you will get a `div` with hello. [Here is a simple demo](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4ADgAo4MAG4QYAd3xwZEoXFqx8UWgHMAlBOQByYxQAExgBIwoO4wF19+yiGmxqxCPQQ8ADIgAjIFsHCCYOHj41HACNPSMzDxsDlRQEGgA1r6o4Vx40nKKrgCuAE7kPCTEYnCIAPT1JWhimbrRtFj1hfIKAAJ++ADs+H71ACYQcMTdsr34-K7EAJ5i3G7UZRBioqwOrEA).

Hope that helps, thanks for your interest in `seview`!

**Comment by futurist** [comment]
I've found `['Hello', 'Hello']` also result in `{tag: 'div'}`, seview not support uppercase as tag string?

**Comment by foxdonut** [comment]
@futurist good point, I will have a look. thanks!

**Comment by foxdonut** [comment]
@futurist tags should be lowercase. If you have a use case for uppercase tag please provide the details, thanks.

**Comment by futurist** [comment]
When for custom elements, at least there's no doc to say only allow lowercase for tag name:

https://github.com/webcomponents/custom-elements

https://github.com/webcomponents/webcomponentsjs
