### ISSUE TITLE
Support tags with uppercase

### ISSUE THREAD

**Issue by foxdonut** [foxdonut/seview#3]
See discussion in #1 as per @futurist

**Comment by foxdonut** [comment]
@futurist fixed in version 0.8.0

**Comment by futurist** [comment]
I think below line constrained custome element can only contain `1-6` numbers:

https://github.com/foxdonut/seview/blob/202d78a1e797fff5e6a6142d9cad0db9b3a50a99/src/util.js#L51

Also, below condition also passed the regex...

```js
/^([A-Za-z1-6-]+)(?::([a-z]+))?/.test('sdoifjo789_*')  //true
```

**Comment by foxdonut** [comment]
@futurist I am using `match`, not `test`, so

```javascript
'sdoifjo789_*'.match(/^([A-Za-z1-6-]+)(?::([a-z]+))?/)
// ["sdoifjo", ...]
```

But you're right, `1-6` should be `0-9`, I fixed that. Thanks!
